In [2]:
import pandas as pd

In [3]:
obstructs_and_sites_df = pd.read_csv('Resources/obstructs_and_sites.csv')

In [4]:
obstructs_and_sites_df

,Record #,Vessel Terms,Feature Type,Lat,Lng,GP Quality,Dive Site Name,Dive Site ID,Distance from Obstruction
0,54094.0,OBSTRUCTION,Obstruction - Submerged,55.934600,-155.540600,NaN,NaN,NaN,NaN
1,53696.0,OBSTRUCTION,Obstruction - Submerged,57.726444,-152.519500,High,NaN,NaN,NaN
2,53695.0,OBSTRUCTION,Obstruction - Submerged,57.721194,-152.526222,High,NaN,NaN,NaN
3,53719.0,OBSTRUCTION,Obstruction - Submerged,54.272833,-164.857167,Low,NaN,NaN,NaN
4,53721.0,OBSTRUCTION,Obstruction - Submerged,54.340000,-164.740167,Low,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6397,14426.0,OBSTRUCTION,Obstruction - Submerged,34.658444,-76.807861,High,Theodore Parker (Liberty Ship) (AR-315),22079.0,2.29
6398,14421.0,OBSTRUCTION,Obstruction - Submerged,34.658194,-76.808500,High,Theodore Parker (Liberty Ship) (AR-315),22079.0,2.32
6399,14431.0,OBSTRUCTION,Obstruction - Submerged,34.655861,-76.808194,High,Theodore Parker (Liberty Ship) (AR-315),22079.0,2.28
6400,14638.0,OBSTRUCTION,Obstruction - Submerged,34.717278,-76.705056,Low,Morehead City railroad bridge,23578.0,1.07
6401,14640.0,OBSTRUCTION,Obstruction - Submerged,34.719944,-76.748639,Low,Morehead City railroad bridge,23578.0,3.51

In [5]:
copy = obstructs_and_sites_df.copy()

In [6]:
copy = copy.dropna(subset = ['Dive Site Name'])

In [11]:
copy["Dive Site ID"] = copy["Dive Site ID"].astype(int)
copy.head()

,Record #,Vessel Terms,Feature Type,Lat,Lng,GP Quality,Dive Site Name,Dive Site ID,Distance from Obstruction
297,8745.0,OBSTRUCTION,Obstruction - Visible at high water,18.312500,-64.958944,Low,Captains Reef USVI,22975,0.94
298,11858.0,OBSTRUCTION,Obstruction - Submerged,18.326656,-64.958092,High,Captains Reef USVI,22975,0.45
299,11859.0,OBSTRUCTION,Obstruction - Submerged,18.330500,-64.960986,Low,Captains Reef USVI,22975,0.75
300,11016.0,OBSTRUCTION,Obstruction - Submerged,17.963672,-66.619553,Med,La Pared de la Parguera,18549,9.73
301,11760.0,OBSTRUCTION,Obstruction - Submerged,18.004511,-66.766511,High,La Pared de la Parguera,18549,3.86

In [12]:
obstructs_and_sites_df = copy

In [13]:
obstructs_df = obstructs_and_sites_df[["Record #", "Vessel Terms", "Feature Type", "Lat", "Lng", "GP Quality"]]
obstructs_df

,Record #,Vessel Terms,Feature Type,Lat,Lng,GP Quality
297,8745.0,OBSTRUCTION,Obstruction - Visible at high water,18.312500,-64.958944,Low
298,11858.0,OBSTRUCTION,Obstruction - Submerged,18.326656,-64.958092,High
299,11859.0,OBSTRUCTION,Obstruction - Submerged,18.330500,-64.960986,Low
300,11016.0,OBSTRUCTION,Obstruction - Submerged,17.963672,-66.619553,Med
301,11760.0,OBSTRUCTION,Obstruction - Submerged,18.004511,-66.766511,High
...,...,...,...,...,...,...
6397,14426.0,OBSTRUCTION,Obstruction - Submerged,34.658444,-76.807861,High
6398,14421.0,OBSTRUCTION,Obstruction - Submerged,34.658194,-76.808500,High
6399,14431.0,OBSTRUCTION,Obstruction - Submerged,34.655861,-76.808194,High
6400,14638.0,OBSTRUCTION,Obstruction - Submerged,34.717278,-76.705056,Low
6401,14640.0,OBSTRUCTION,Obstruction - Submerged,34.719944,-76.748639,Low

In [14]:
obstructs_df.to_csv("Resources/obstructs_transformed.csv", index = False)

In [17]:
dive_sites_df = obstructs_and_sites_df[["Dive Site ID", "Dive Site Name", "Distance from Obstruction", 
                                     "Lat", "Lng", "Record #"]]

In [18]:
dive_sites_df

,Dive Site ID,Dive Site Name,Distance from Obstruction,Lat,Lng,Record #
297,22975,Captains Reef USVI,0.94,18.312500,-64.958944,8745.0
298,22975,Captains Reef USVI,0.45,18.326656,-64.958092,11858.0
299,22975,Captains Reef USVI,0.75,18.330500,-64.960986,11859.0
300,18549,La Pared de la Parguera,9.73,17.963672,-66.619553,11016.0
301,18549,La Pared de la Parguera,3.86,18.004511,-66.766511,11760.0
...,...,...,...,...,...,...
6397,22079,Theodore Parker (Liberty Ship) (AR-315),2.29,34.658444,-76.807861,14426.0
6398,22079,Theodore Parker (Liberty Ship) (AR-315),2.32,34.658194,-76.808500,14421.0
6399,22079,Theodore Parker (Liberty Ship) (AR-315),2.28,34.655861,-76.808194,14431.0
6400,23578,Morehead City railroad bridge,1.07,34.717278,-76.705056,14638.0
6401,23578,Morehead City railroad bridge,3.51,34.719944,-76.748639,14640.0

In [19]:
dive_sites_df.to_csv("Resources/o_dive_sites_transformed.csv", index = False)