In [18]:
from config import w_key
import requests
import json
import pandas as pd

In [19]:
path = "Resources/us_station_id.csv"
coord_csv = pd.read_csv(path)
coord_csv

      Station ID        Lat         Lng
0          25704  51.883583 -176.642481
1          26610  62.500000 -164.420000
2          45701  52.830000  173.320000
3          25502  56.899487 -154.247847
4          26515  66.551833 -152.622167
...          ...        ...         ...
3430       94053  42.064528 -104.152694
3431       24082  42.000000 -104.166700
3432       24083  42.066700 -104.966700
3433       24062  43.962889 -107.950528
3434       94173  44.550000 -110.416700

[3435 rows x 3 columns]

In [21]:
path = "Resources/coops-activecurrentstations.csv"
curr_csv = pd.read_csv(path)
curr_csv

,Station ID,Station Name,Latitude,Longitude,Project
0,ca0101,Cape Cod Canal West End,41.737499,-70.624901,Cape Cod PORTS
1,cb0102,Cape Henry LB 2CH,36.959400,-76.012800,Chesapeake Bay South PORTS
2,cb0201,York Spit LBB 22 (ATON),37.140000,-76.138300,Chesapeake Bay South PORTS
3,cb0301,Thimble Shoal LB 18,37.011080,-76.249030,Chesapeake Bay South PORTS
4,cb0402,Naval Station Norfolk LB 7,36.962950,-76.333880,Chesapeake Bay South PORTS
...,...,...,...,...,...
60,sn0701,Port Arthur,29.866700,-93.931110,Sabine Neches PORTS
61,t01010,Sunshine Skyway Bridge ADCP,27.620650,-82.655250,Tampa Bay PORTS
62,t02010,Old Port Tampa,27.862870,-82.553730,Tampa Bay PORTS
63,t03010,Port Manatee,27.663950,-82.598770,Tampa Bay PORTS
64,t04010,Egmont Channel LB 9,27.604240,-82.867420,Tampa Bay PORTS

In [10]:
#TO TEST A DIFFERENT TYPE OF CURRENT API CALL.... Ignore this one

url = f"https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9414290/nearby.json?radius=3"
#url = f"https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/lat/51.883583/lng/-176.642481/nearby.json?radius=3"
response = requests.get(url).json()
print(json.dumps(response, indent=4, sort_keys=True))

{
    "count": null,
    "self": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/45701/nearby.json",
    "stations": [],
    "units": null
}

In [23]:
#TO TEST STATION IDS
url = f"https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?date=today&station=ca0101&product=currents&units=english&time_zone=gmt&application=ports_screen&format=json"
response = requests.get(url).json()
print(json.dumps(response, indent=4, sort_keys=True))

{
    "data": [
        {
            "b": "20",
            "d": "44",
            "s": "3.752",
            "t": "2020-12-02 00:04"
        },
        {
            "b": "20",
            "d": "42",
            "s": "3.884",
            "t": "2020-12-02 00:10"
        },
        {
            "b": "20",
            "d": "42",
            "s": "3.806",
            "t": "2020-12-02 00:16"
        },
        {
            "b": "20",
            "d": "43",
            "s": "3.682",
            "t": "2020-12-02 00:22"
        },
        {
            "b": "20",
            "d": "43",
            "s": "3.472",
            "t": "2020-12-02 00:28"
        },
        {
            "b": "20",
            "d": "42",
            "s": "3.699",
            "t": "2020-12-02 00:34"
        },
        {
            "b": "20",
            "d": "42",
            "s": "3.682",
            "t": "2020-12-02 00:40"
        },
        {
            "b": "20",
            "d": "43",
            "s": "3.831",
            "t": "2020-12-02 00:46"
        },
        {
            "b": "20",
            "d": "44",
            "s": "3.695",
            "t": "2020-12-02 00:52"
        },
        {
            "b": "20",
            "d": "45",
            "s": "3.742",
            "t": "2020-12-02 00:58"
        },
        {
            "b": "20",
            "d": "42",
            "s": "3.351",
            "t": "2020-12-02 01:04"
        },
        {
            "b": "20",
            "d": "43",
            "s": "3.433",
            "t": "2020-12-02 01:10"
        },
        {
            "b": "20",
            "d": "41",
            "s": "3.435",
            "t": "2020-12-02 01:16"
        },
        {
            "b": "20",
            "d": "43",
            "s": "3.417",
            "t": "2020-12-02 01:22"
        },
        {
            "b": "20",
            "d": "42",
            "s": "3.287",
            "t": "2020-12-02 01:28"
        }
    ],
    "metadata": {
        "id": "ca0101",
        "lat": "41.7375",
        "lon": "-70.6249",
        "name": "Cape Cod Canal, West End"
    }
}

In [16]:

#Open weather query
units = "standard"
#lats = coord_csv["Lng"]
#lons = coord_csv["Lat"]

lats = ["51.883583"]
lons = ["-176.642481"]

#Tide query
#begin = "20130101 10:00"
#end = "20130101 10:24"
date = "today"
product = "current_prediction"

station = ["8454000"]
datum = "MTL"
unit = "metric"
time = "lst"
format_j = "json"
app = "data_bootcamp"


#for (lat, lon) in zip(lats, lons):
    #w_url= f"http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&units={units}&appid={w_key}"
    #w_query= requests.get(w_url).json()
    #temp_get = w_query['main']['temp']
    #temps.append(temp_get)
    
for station in stations:
    t_url = f"https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?date={date}&station={station}&product={product}&datum={datum}&units={unit}&time_zone={time}&application={app}&format={format_j}"
    t_query = requests.get(t_url).json()
    currents = t_query["current_predictions"][]
    
    
#Outputs    
temps = []